### ISSUE TITLE
SpigotMC download link is broken

### ISSUE THREAD

**Issue by Dymeth** [lvinci/bungeeban#2]
[SpigotMC](https://spigotmc.org/resources/5924) redirects to a link for a release that is currently unavailable:
https://github.com/lucavinci/bungeeban/releases/download/v2.7.0/bungeeban-2.7.0.jar

**Comment by lucavinci** [comment]
Oh snap, I have not maintained my spigot account for several years. I will try to change it this weekend.

**Comment by Dymeth** [comment]
Not sure if this is still relevant
